# Generated by Django 5.2.2 on 2025-06-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_ranking",
                    models.CharField(
                        default="Ranking de Alumnos",
                        help_text="Título principal que se mostrará en la página del ranking.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Ranking",
                "verbose_name_plural": "Configuración del Ranking",
            },
        ),
    ]
