# Generated by Django 5.2.2 on 2025-06-10 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("puntos", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "ordering": ["-puntos", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID único para compartir la partida",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la partida (ej. 'Competencia de Programación').",
                        max_length=200,
                    ),
                ),
                (
                    "admin_password_hash",
                    models.CharField(
                        help_text="contraseña para administrar la partida",
                        max_length=128,
                    ),
                ),
                (
                    "timer_duration_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Duración total del temporizador en segundos. (0=sin temporizador)",
                    ),
                ),
                (
                    "timer_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que el temporizador fue iniciado por última vez",
                        null=True,
                    ),
                ),
                (
                    "timer_paused_at_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Segundos restantes cuando el temporizador fue pausado",
                    ),
                ),
                (
                    "timer_is_running",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el temporizador está actualmente en ejecución",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Partida de Ranking",
                "verbose_name_plural": "Partidas de Ranking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ConfiguracionRanking",
        ),
        migrations.AddField(
            model_name="alumno",
            name="partida",
            field=models.ForeignKey(
                help_text="Partida a la que pertenece este alumno.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alumnos",
                to="alumnos.partida",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alumno",
            unique_together={("partida", "nombre")},
        ),
    ]
