# Generated by Django 5.2.2 on 2025-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_alumno_partida_delete_configuracionranking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partida",
            name="admin_password_hash",
            field=models.CharField(
                help_text="contraseña para administrar la partida", max_length=4
            ),
        ),
    ]
