# Generated by Django 5.2.2 on 2025-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_alter_partida_admin_password_hash"),
    ]

    operations = [


    ]
