# Generated by Django 5.2.2 on 2025-06-10 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0003_alter_partida_admin_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="partida",
            name="short_code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
