# Generated by Django 5.2.2 on 2025-06-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0003_auto_20250611_1907"),
    ]

    operations = []
